version: '3.8'

services:
  icon-manager-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"  # 后端API端口
      - "5173:5173"  # 前端开发服务器端口
    volumes:
      # 图片文件夹映射到宿主机，支持实时同步
      - ./public/assets/images:/app/public/assets/images
      # 实时代码更新
      - ./client/src:/app/client/src
      - ./node-functions:/app/node-functions
      - ./package.json:/app/package.json
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3000
      - PORT=3000
    restart: unless-stopped
    networks:
      - icon-network

networks:
  icon-network:
    driver: bridge

volumes:
  # 持久化图片数据
  images_data:
    driver: local

